services:
  django:
    build: ./backend
    tty: true
    stdin_open: true
    ports:
      - "8001:8001"
    volumes:
      - ./backend/:/app
  react:
    build: ./frontend
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
