services:
  django:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
  react:
    build: ./frontend
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
